// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406214648_AddLighthouseTables")]
    partial class AddLighthouseTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .HasColumnType("int")
                        .HasColumnName("donation_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CampaignName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("campaign_name");

                    b.Property<string>("ChannelSource")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("channel_source");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency_code");

                    b.Property<DateOnly>("DonationDate")
                        .HasColumnType("date")
                        .HasColumnName("donation_date");

                    b.Property<string>("DonationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("donation_type");

                    b.Property<decimal?>("EstimatedValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("estimated_value");

                    b.Property<string>("ImpactUnit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("impact_unit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit")
                        .HasColumnName("is_recurring");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int?>("ReferralPostId")
                        .HasColumnType("int")
                        .HasColumnName("referral_post_id");

                    b.Property<int>("SupporterId")
                        .HasColumnType("int")
                        .HasColumnName("supporter_id");

                    b.HasKey("DonationId");

                    b.HasIndex("ReferralPostId");

                    b.HasIndex("SupporterId");

                    b.ToTable("donations", (string)null);
                });

            modelBuilder.Entity("api.Models.DonationAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .HasColumnType("int")
                        .HasColumnName("allocation_id");

                    b.Property<DateOnly>("AllocationDate")
                        .HasColumnType("date")
                        .HasColumnName("allocation_date");

                    b.Property<string>("AllocationNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("allocation_notes");

                    b.Property<decimal>("AmountAllocated")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_allocated");

                    b.Property<int>("DonationId")
                        .HasColumnType("int")
                        .HasColumnName("donation_id");

                    b.Property<string>("ProgramArea")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("program_area");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    b.HasKey("AllocationId");

                    b.HasIndex("DonationId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("donation_allocations", (string)null);
                });

            modelBuilder.Entity("api.Models.EducationRecord", b =>
                {
                    b.Property<int>("EducationRecordId")
                        .HasColumnType("int")
                        .HasColumnName("education_record_id");

                    b.Property<double?>("AttendanceRate")
                        .HasColumnType("float")
                        .HasColumnName("attendance_rate");

                    b.Property<string>("CompletionStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("completion_status");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("education_level");

                    b.Property<string>("EnrollmentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("enrollment_status");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<double?>("ProgressPercent")
                        .HasColumnType("float")
                        .HasColumnName("progress_percent");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date")
                        .HasColumnName("record_date");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<string>("SchoolName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("school_name");

                    b.HasKey("EducationRecordId");

                    b.HasIndex("ResidentId");

                    b.ToTable("education_records", (string)null);
                });

            modelBuilder.Entity("api.Models.HealthWellbeingRecord", b =>
                {
                    b.Property<int>("HealthRecordId")
                        .HasColumnType("int")
                        .HasColumnName("health_record_id");

                    b.Property<double?>("Bmi")
                        .HasColumnType("float")
                        .HasColumnName("bmi");

                    b.Property<bool>("DentalCheckupDone")
                        .HasColumnType("bit")
                        .HasColumnName("dental_checkup_done");

                    b.Property<double?>("EnergyLevelScore")
                        .HasColumnType("float")
                        .HasColumnName("energy_level_score");

                    b.Property<double?>("GeneralHealthScore")
                        .HasColumnType("float")
                        .HasColumnName("general_health_score");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("float")
                        .HasColumnName("height_cm");

                    b.Property<bool>("MedicalCheckupDone")
                        .HasColumnType("bit")
                        .HasColumnName("medical_checkup_done");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<double?>("NutritionScore")
                        .HasColumnType("float")
                        .HasColumnName("nutrition_score");

                    b.Property<bool>("PsychologicalCheckupDone")
                        .HasColumnType("bit")
                        .HasColumnName("psychological_checkup_done");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date")
                        .HasColumnName("record_date");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<double?>("SleepQualityScore")
                        .HasColumnType("float")
                        .HasColumnName("sleep_quality_score");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("float")
                        .HasColumnName("weight_kg");

                    b.HasKey("HealthRecordId");

                    b.HasIndex("ResidentId");

                    b.ToTable("health_wellbeing_records", (string)null);
                });

            modelBuilder.Entity("api.Models.HomeVisitation", b =>
                {
                    b.Property<int>("VisitationId")
                        .HasColumnType("int")
                        .HasColumnName("visitation_id");

                    b.Property<string>("FamilyCooperationLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("family_cooperation_level");

                    b.Property<string>("FamilyMembersPresent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("family_members_present");

                    b.Property<bool>("FollowUpNeeded")
                        .HasColumnType("bit")
                        .HasColumnName("follow_up_needed");

                    b.Property<string>("FollowUpNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("follow_up_notes");

                    b.Property<string>("LocationVisited")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("location_visited");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observations");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("purpose");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<bool>("SafetyConcernsNoted")
                        .HasColumnType("bit")
                        .HasColumnName("safety_concerns_noted");

                    b.Property<string>("SocialWorker")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("social_worker");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date")
                        .HasColumnName("visit_date");

                    b.Property<string>("VisitOutcome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("visit_outcome");

                    b.Property<string>("VisitType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("visit_type");

                    b.HasKey("VisitationId");

                    b.HasIndex("ResidentId");

                    b.ToTable("home_visitations", (string)null);
                });

            modelBuilder.Entity("api.Models.InKindDonationItem", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int>("DonationId")
                        .HasColumnType("int")
                        .HasColumnName("donation_id");

                    b.Property<decimal?>("EstimatedUnitValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("estimated_unit_value");

                    b.Property<string>("IntendedUse")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("intended_use");

                    b.Property<string>("ItemCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("item_category");

                    b.Property<string>("ItemName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("item_name");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantity");

                    b.Property<string>("ReceivedCondition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("received_condition");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("unit_of_measure");

                    b.HasKey("ItemId");

                    b.HasIndex("DonationId");

                    b.ToTable("in_kind_donation_items", (string)null);
                });

            modelBuilder.Entity("api.Models.IncidentReport", b =>
                {
                    b.Property<int>("IncidentId")
                        .HasColumnType("int")
                        .HasColumnName("incident_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("FollowUpRequired")
                        .HasColumnType("bit")
                        .HasColumnName("follow_up_required");

                    b.Property<DateOnly>("IncidentDate")
                        .HasColumnType("date")
                        .HasColumnName("incident_date");

                    b.Property<string>("IncidentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("incident_type");

                    b.Property<string>("ReportedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("reported_by");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<DateOnly?>("ResolutionDate")
                        .HasColumnType("date")
                        .HasColumnName("resolution_date");

                    b.Property<bool>("Resolved")
                        .HasColumnType("bit")
                        .HasColumnName("resolved");

                    b.Property<string>("ResponseTaken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_taken");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Severity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("severity");

                    b.HasKey("IncidentId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("incident_reports", (string)null);
                });

            modelBuilder.Entity("api.Models.InterventionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<DateOnly?>("CaseConferenceDate")
                        .HasColumnType("date")
                        .HasColumnName("case_conference_date");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("PlanCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("plan_category");

                    b.Property<string>("PlanDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("plan_description");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<string>("ServicesProvided")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("services_provided");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("target_date");

                    b.Property<double?>("TargetValue")
                        .HasColumnType("float")
                        .HasColumnName("target_value");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("PlanId");

                    b.HasIndex("ResidentId");

                    b.ToTable("intervention_plans", (string)null);
                });

            modelBuilder.Entity("api.Models.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .HasColumnType("int")
                        .HasColumnName("partner_id");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("contact_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("partner_name");

                    b.Property<string>("PartnerType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("partner_type");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("region");

                    b.Property<string>("RoleType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("role_type");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("PartnerId");

                    b.ToTable("partners", (string)null);
                });

            modelBuilder.Entity("api.Models.PartnerAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    b.Property<DateOnly?>("AssignmentEnd")
                        .HasColumnType("date")
                        .HasColumnName("assignment_end");

                    b.Property<DateOnly>("AssignmentStart")
                        .HasColumnType("date")
                        .HasColumnName("assignment_start");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit")
                        .HasColumnName("is_primary");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int")
                        .HasColumnName("partner_id");

                    b.Property<string>("ProgramArea")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("program_area");

                    b.Property<string>("ResponsibilityNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("responsibility_notes");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("AssignmentId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("partner_assignments", (string)null);
                });

            modelBuilder.Entity("api.Models.ProcessRecording", b =>
                {
                    b.Property<int>("RecordingId")
                        .HasColumnType("int")
                        .HasColumnName("recording_id");

                    b.Property<bool>("ConcernsFlagged")
                        .HasColumnType("bit")
                        .HasColumnName("concerns_flagged");

                    b.Property<string>("EmotionalStateEnd")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("emotional_state_end");

                    b.Property<string>("EmotionalStateObserved")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("emotional_state_observed");

                    b.Property<string>("FollowUpActions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("follow_up_actions");

                    b.Property<string>("InterventionsApplied")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("interventions_applied");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes_restricted");

                    b.Property<bool>("ProgressNoted")
                        .HasColumnType("bit")
                        .HasColumnName("progress_noted");

                    b.Property<bool>("ReferralMade")
                        .HasColumnType("bit")
                        .HasColumnName("referral_made");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date")
                        .HasColumnName("session_date");

                    b.Property<int?>("SessionDurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("session_duration_minutes");

                    b.Property<string>("SessionNarrative")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("session_narrative");

                    b.Property<string>("SessionType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("session_type");

                    b.Property<string>("SocialWorker")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("social_worker");

                    b.HasKey("RecordingId");

                    b.HasIndex("ResidentId");

                    b.ToTable("process_recordings", (string)null);
                });

            modelBuilder.Entity("api.Models.PublicImpactSnapshot", b =>
                {
                    b.Property<int>("SnapshotId")
                        .HasColumnType("int")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("Headline")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("headline");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit")
                        .HasColumnName("is_published");

                    b.Property<string>("MetricPayloadJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metric_payload_json");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("published_at");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date");

                    b.Property<string>("SummaryText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary_text");

                    b.HasKey("SnapshotId");

                    b.ToTable("public_impact_snapshots", (string)null);
                });

            modelBuilder.Entity("api.Models.Resident", b =>
                {
                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<string>("AgeUponAdmission")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("age_upon_admission");

                    b.Property<string>("AssignedSocialWorker")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("assigned_social_worker");

                    b.Property<string>("BirthStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("birth_status");

                    b.Property<string>("CaseCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("case_category");

                    b.Property<string>("CaseControlNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("case_control_no");

                    b.Property<string>("CaseStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("case_status");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentRiskLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("current_risk_level");

                    b.Property<DateOnly?>("DateCaseStudyPrepared")
                        .HasColumnType("date")
                        .HasColumnName("date_case_study_prepared");

                    b.Property<DateOnly?>("DateClosed")
                        .HasColumnType("date")
                        .HasColumnName("date_closed");

                    b.Property<DateOnly?>("DateColbObtained")
                        .HasColumnType("date")
                        .HasColumnName("date_colb_obtained");

                    b.Property<DateOnly?>("DateColbRegistered")
                        .HasColumnType("date")
                        .HasColumnName("date_colb_registered");

                    b.Property<DateOnly?>("DateEnrolled")
                        .HasColumnType("date")
                        .HasColumnName("date_enrolled");

                    b.Property<DateOnly?>("DateOfAdmission")
                        .HasColumnType("date")
                        .HasColumnName("date_of_admission");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<bool>("FamilyIndigenous")
                        .HasColumnType("bit")
                        .HasColumnName("family_indigenous");

                    b.Property<bool>("FamilyInformalSettler")
                        .HasColumnType("bit")
                        .HasColumnName("family_informal_settler");

                    b.Property<bool>("FamilyIs4ps")
                        .HasColumnType("bit")
                        .HasColumnName("family_is_4ps");

                    b.Property<bool>("FamilyParentPwd")
                        .HasColumnType("bit")
                        .HasColumnName("family_parent_pwd");

                    b.Property<bool>("FamilySoloParent")
                        .HasColumnType("bit")
                        .HasColumnName("family_solo_parent");

                    b.Property<bool>("HasSpecialNeeds")
                        .HasColumnType("bit")
                        .HasColumnName("has_special_needs");

                    b.Property<string>("InitialCaseAssessment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("initial_case_assessment");

                    b.Property<string>("InitialRiskLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("initial_risk_level");

                    b.Property<string>("InternalCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("internal_code");

                    b.Property<bool>("IsPwd")
                        .HasColumnType("bit")
                        .HasColumnName("is_pwd");

                    b.Property<string>("LengthOfStay")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("length_of_stay");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes_restricted");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("place_of_birth");

                    b.Property<string>("PresentAge")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("present_age");

                    b.Property<string>("PwdType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("pwd_type");

                    b.Property<string>("ReferralSource")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("referral_source");

                    b.Property<string>("ReferringAgencyPerson")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("referring_agency_person");

                    b.Property<string>("ReintegrationStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("reintegration_status");

                    b.Property<string>("ReintegrationType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("reintegration_type");

                    b.Property<string>("Religion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("religion");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    b.Property<string>("Sex")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sex");

                    b.Property<string>("SpecialNeedsDiagnosis")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("special_needs_diagnosis");

                    b.Property<bool>("SubCatAtRisk")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_at_risk");

                    b.Property<bool>("SubCatChildLabor")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_child_labor");

                    b.Property<bool>("SubCatChildWithHiv")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_child_with_hiv");

                    b.Property<bool>("SubCatCicl")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_cicl");

                    b.Property<bool>("SubCatOrphaned")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_orphaned");

                    b.Property<bool>("SubCatOsaec")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_osaec");

                    b.Property<bool>("SubCatPhysicalAbuse")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_physical_abuse");

                    b.Property<bool>("SubCatSexualAbuse")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_sexual_abuse");

                    b.Property<bool>("SubCatStreetChild")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_street_child");

                    b.Property<bool>("SubCatTrafficked")
                        .HasColumnType("bit")
                        .HasColumnName("sub_cat_trafficked");

                    b.HasKey("ResidentId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("residents", (string)null);
                });

            modelBuilder.Entity("api.Models.Safehouse", b =>
                {
                    b.Property<int>("SafehouseId")
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    b.Property<int?>("CapacityGirls")
                        .HasColumnType("int")
                        .HasColumnName("capacity_girls");

                    b.Property<int?>("CapacityStaff")
                        .HasColumnType("int")
                        .HasColumnName("capacity_staff");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("country");

                    b.Property<int?>("CurrentOccupancy")
                        .HasColumnType("int")
                        .HasColumnName("current_occupancy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("OpenDate")
                        .HasColumnType("date")
                        .HasColumnName("open_date");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("province");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("region");

                    b.Property<string>("SafehouseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("safehouse_code");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("SafehouseId");

                    b.ToTable("safehouses", (string)null);
                });

            modelBuilder.Entity("api.Models.SafehouseMonthlyMetric", b =>
                {
                    b.Property<int>("MetricId")
                        .HasColumnType("int")
                        .HasColumnName("metric_id");

                    b.Property<int?>("ActiveResidents")
                        .HasColumnType("int")
                        .HasColumnName("active_residents");

                    b.Property<double?>("AvgEducationProgress")
                        .HasColumnType("float")
                        .HasColumnName("avg_education_progress");

                    b.Property<double?>("AvgHealthScore")
                        .HasColumnType("float")
                        .HasColumnName("avg_health_score");

                    b.Property<int?>("HomeVisitationCount")
                        .HasColumnType("int")
                        .HasColumnName("home_visitation_count");

                    b.Property<int?>("IncidentCount")
                        .HasColumnType("int")
                        .HasColumnName("incident_count");

                    b.Property<DateOnly>("MonthEnd")
                        .HasColumnType("date")
                        .HasColumnName("month_end");

                    b.Property<DateOnly>("MonthStart")
                        .HasColumnType("date")
                        .HasColumnName("month_start");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int?>("ProcessRecordingCount")
                        .HasColumnType("int")
                        .HasColumnName("process_recording_count");

                    b.Property<int>("SafehouseId")
                        .HasColumnType("int")
                        .HasColumnName("safehouse_id");

                    b.HasKey("MetricId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("safehouse_monthly_metrics", (string)null);
                });

            modelBuilder.Entity("api.Models.SocialMediaPost", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<double?>("AvgViewDurationSeconds")
                        .HasColumnType("float")
                        .HasColumnName("avg_view_duration_seconds");

                    b.Property<decimal?>("BoostBudgetPhp")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("boost_budget_php");

                    b.Property<string>("CallToActionType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("call_to_action_type");

                    b.Property<string>("CampaignName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("campaign_name");

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("caption");

                    b.Property<int?>("CaptionLength")
                        .HasColumnType("int")
                        .HasColumnName("caption_length");

                    b.Property<int?>("ClickThroughs")
                        .HasColumnType("int")
                        .HasColumnName("click_throughs");

                    b.Property<int?>("Comments")
                        .HasColumnType("int")
                        .HasColumnName("comments");

                    b.Property<string>("ContentTopic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("content_topic");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DayOfWeek")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("day_of_week");

                    b.Property<int?>("DonationReferrals")
                        .HasColumnType("int")
                        .HasColumnName("donation_referrals");

                    b.Property<double?>("EngagementRate")
                        .HasColumnType("float")
                        .HasColumnName("engagement_rate");

                    b.Property<decimal?>("EstimatedDonationValuePhp")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("estimated_donation_value_php");

                    b.Property<bool?>("FeaturesResidentStory")
                        .HasColumnType("bit")
                        .HasColumnName("features_resident_story");

                    b.Property<int?>("FollowerCountAtPost")
                        .HasColumnType("int")
                        .HasColumnName("follower_count_at_post");

                    b.Property<double?>("Forwards")
                        .HasColumnType("float")
                        .HasColumnName("forwards");

                    b.Property<bool?>("HasCallToAction")
                        .HasColumnType("bit")
                        .HasColumnName("has_call_to_action");

                    b.Property<string>("Hashtags")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hashtags");

                    b.Property<int?>("Impressions")
                        .HasColumnType("int")
                        .HasColumnName("impressions");

                    b.Property<bool?>("IsBoosted")
                        .HasColumnType("bit")
                        .HasColumnName("is_boosted");

                    b.Property<int?>("Likes")
                        .HasColumnType("int")
                        .HasColumnName("likes");

                    b.Property<string>("MediaType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("media_type");

                    b.Property<int?>("MentionsCount")
                        .HasColumnType("int")
                        .HasColumnName("mentions_count");

                    b.Property<int?>("NumHashtags")
                        .HasColumnType("int")
                        .HasColumnName("num_hashtags");

                    b.Property<string>("Platform")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("platform");

                    b.Property<string>("PlatformPostId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("platform_post_id");

                    b.Property<int?>("PostHour")
                        .HasColumnType("int")
                        .HasColumnName("post_hour");

                    b.Property<string>("PostType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("post_type");

                    b.Property<string>("PostUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("post_url");

                    b.Property<int?>("ProfileVisits")
                        .HasColumnType("int")
                        .HasColumnName("profile_visits");

                    b.Property<int?>("Reach")
                        .HasColumnType("int")
                        .HasColumnName("reach");

                    b.Property<int?>("Saves")
                        .HasColumnType("int")
                        .HasColumnName("saves");

                    b.Property<string>("SentimentTone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sentiment_tone");

                    b.Property<int?>("Shares")
                        .HasColumnType("int")
                        .HasColumnName("shares");

                    b.Property<int?>("SubscriberCountAtPost")
                        .HasColumnType("int")
                        .HasColumnName("subscriber_count_at_post");

                    b.Property<int?>("VideoViews")
                        .HasColumnType("int")
                        .HasColumnName("video_views");

                    b.Property<int?>("WatchTimeSeconds")
                        .HasColumnType("int")
                        .HasColumnName("watch_time_seconds");

                    b.HasKey("PostId");

                    b.ToTable("social_media_posts", (string)null);
                });

            modelBuilder.Entity("api.Models.Supporter", b =>
                {
                    b.Property<int>("SupporterId")
                        .HasColumnType("int")
                        .HasColumnName("supporter_id");

                    b.Property<string>("AcquisitionChannel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("acquisition_channel");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("country");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("FirstDonationDate")
                        .HasColumnType("date")
                        .HasColumnName("first_donation_date");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("organization_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("region");

                    b.Property<string>("RelationshipType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("relationship_type");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("SupporterType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("supporter_type");

                    b.HasKey("SupporterId");

                    b.ToTable("supporters", (string)null);
                });

            modelBuilder.Entity("api.Models.Donation", b =>
                {
                    b.HasOne("api.Models.SocialMediaPost", null)
                        .WithMany()
                        .HasForeignKey("ReferralPostId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Models.Supporter", null)
                        .WithMany()
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.DonationAllocation", b =>
                {
                    b.HasOne("api.Models.Donation", null)
                        .WithMany()
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Safehouse", null)
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.EducationRecord", b =>
                {
                    b.HasOne("api.Models.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.HealthWellbeingRecord", b =>
                {
                    b.HasOne("api.Models.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.HomeVisitation", b =>
                {
                    b.HasOne("api.Models.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.InKindDonationItem", b =>
                {
                    b.HasOne("api.Models.Donation", null)
                        .WithMany()
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.IncidentReport", b =>
                {
                    b.HasOne("api.Models.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("api.Models.Safehouse", null)
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.InterventionPlan", b =>
                {
                    b.HasOne("api.Models.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.PartnerAssignment", b =>
                {
                    b.HasOne("api.Models.Partner", null)
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("api.Models.Safehouse", null)
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.ProcessRecording", b =>
                {
                    b.HasOne("api.Models.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.Resident", b =>
                {
                    b.HasOne("api.Models.Safehouse", null)
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.SafehouseMonthlyMetric", b =>
                {
                    b.HasOne("api.Models.Safehouse", null)
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
