services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: keeper-sqlserver
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: keeper123
      MSSQL_DB: keeper
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
